# Generated by Django 3.1 on 2021-10-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20210929_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='status',
        ),
        migrations.AddField(
            model_name='order_product',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='payment_status',
            field=models.CharField(blank=True, default='not done', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='order_product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[['order_confirmed', 'order_confirmed'], ['shipped', 'shipped'], ['out_for_delivery', 'out_for_delivery'], ['delivered', 'delivered']], max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.order_product')),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
