# Generated by Django 3.1 on 2021-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20211011_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='mobile1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='mobile2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
