# Generated by Django 3.1 on 2021-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20211011_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_product_detail',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
